### ISSUE TITLE
Avoid functions returning functions

### ISSUE THREAD

**Issue by vdemedes** [avajs/ava-files#1]
This question has been in my head for a long time. I don't understand what's the point/benefit of having `makeTestMatcher` and `makeSourceMatcher`, which return functions. 

Take the following example from the readme:

```js
const isTest = avaFiles.makeTestMatcher();

isTest(filePath);
//=> true or false

const isSource = avaFiles.makeSourceMatcher();

isSource(filePath);
//=> true or false
```

What we could have instead:

```js
const isTest = avaFiles.isTest(filePath);
// true or false

const isSource = avaFiles.isSource(filePath);
// true or false
```

The API is simpler & nicer, does not make & return functions and can be used in `filter` or `map` the same way.

**Comment by jamestalmage** [comment]
:+1:

**Comment by novemberborn** [comment]
IIRC those factory methods originally closed over variables that were not available where the returned methods were called. That's not the case now `AvaFiles` is a class.

**Comment by vdemedes** [comment]
PR is in the making.

**Comment by vdemedes** [comment]
I'm short on time nowadays, if someone wants to pick this up, please do :)
