### ISSUE TITLE
Move back into AVA proper

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava-files#11]
https://github.com/avajs/ava/pull/925 mentions the code was extracted to "allow other tools (i.e. atom-ava, linter, etc) to have access to the file selection logic."

I don't [see it in `atom-ava`'s dependencies](https://github.com/avajs/atom-ava/blob/639c2e649a26bbbdbd7d4dd002da1ca004f01f98/package.json#L39:L41) though.

Given the tight coupling I think it's easier if we can maintain this in AVA itself. We'll have to use TAP again for tests, so that sucks, but thinking about compatibility with current AVA releases sucks more IMHO.

@avajs/core?

**Comment by sotojuan** [comment]
I think if no one has really found a use for it outside of AVA it's safe to put it back, but we should make sure no projects actually use it.

**Comment by sindresorhus** [comment]
I agree. In hindsight, I think we should have only done it out of actual need, not imaginary future need.

Doesn't look like anyone is using it anyways: https://www.npmjs.com/browse/depended/ava-files

**Comment by novemberborn** [comment]
Cool, I'll raise a ticket with AVA itself.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/avajs/ava/pull/1196
