### ISSUE TITLE
Ignore relativeness in patterns

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava-files#6]
Patterns starting with `./`, e.g. `./test/myTest.js` should be treated as `test/myTest.js`. Otherwise they won't match change events from Chokidar, which ends up emitting the changed paths as `test/myTest.js`.

**Comment by sotojuan** [comment]
Is this just a matter of replacing `./` at the beginning of pattern with nothing? (`./hello` -> `hello`).

**Comment by novemberborn** [comment]
That'd probably be a good solution, yea!

**Comment by alathon** [comment]
Isn't ./A/./B/././ technically a valid path for A/B ? I.e. replace *any* occurrence of ./ after a / with nothing.

**Comment by novemberborn** [comment]
> Isn't ./A/./B/././ technically a valid path for A/B ? I.e. strip prefix ./, replace /./ with /, strip postfix /
> 
> Bit contrived, though.

Maybe, but these patterns are processed by a variety of other packages… let's normalize the obvious stuff first.

**Comment by novemberborn** [comment]
I realize I should have dug a little deeper. The problem is the `isTest` function not matching `test/foo.js` if the pattern is `./test/foo.js`. That assumption is actually stated in the code: https://github.com/avajs/ava-files/blob/f4daaa5af152cebb4a59bd98400fc60edd5a456a/index.js#L145:L146.

We thus need to normalize the patterns in the constructor (https://github.com/avajs/ava-files/blob/f4daaa5af152cebb4a59bd98400fc60edd5a456a/index.js#L37).

**Comment by sotojuan** [comment]
> We thus need to normalize the patterns in the constructor

Does this just mean moving the

```js
files.map(function (file) {
  if (file.slice(0, 2) === './') {
    return file.slice(2);
  }

  return file;
});
```

to the constructor?

/cc @sindresorhus

**Comment by novemberborn** [comment]
@sotojuan yes.
